apiVersion: apps/v1
kind: Deployment
metadata:
  name: estadisticas-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estadisticas
  template:
    metadata:
      labels:
        app: estadisticas
    spec:
      containers:
      - name: estadisticas
        image: 914091100375.dkr.ecr.us-east-1.amazonaws.com/estadisticas:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: casino-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: estadisticas-service
spec:
  type: ClusterIP
  selector:
    app: estadisticas
  ports:
  - port: 3000
    targetPort: 3000