apiVersion: apps/v1
kind: Deployment
metadata:
  name: estadisticas-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estadisticas
  template:
    metadata:
      labels:
        app: estadisticas
    spec:
      containers:
      - name: estadisticas
        image: 914091100375.dkr.ecr.us-east-1.amazonaws.com/estadisticas-service:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8006
        # CAMBIO: Inyectamos el host de la BD para que el código no busque localhost
        env:
        - name: DB_HOST
          value: "postgres-service"
        envFrom:
        - secretRef:
            name: casino-secrets
        # CAMBIO: Agregamos las sondas de salud que definiste en tu código
        livenessProbe:
          httpGet:
            path: /livez
            port: 8006
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8006
          initialDelaySeconds: 10
